jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=BOM_DB;encrypt=false;trustServerCertificate=true;sendStringParametersAsUnicode=true
jdbc.username=sa
jdbc.password=Sync@2026
